artifact_root: aritfacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_data: poultry_diseases.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion
